# Exercise: Using `Plotly` to create a simple bar chart

In this exercise, you'll be practicing the same 20 and 50-day moving average chart from the `matplotlib` exercise, but using `plotly`.

**Download historical data for 2 years from one ticker**

Use the YFinance package to download 2 years of data for any ticker you'd like.

In [7]:
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go

In [8]:
stock_ticker = "000660.KS"
start_date = "2024-05-01"  # use format YYYY-MM-DD
end_date = "2026-05-11"

data = yf.download(
    tickers=stock_ticker, start=start_date, end=end_date
)  # replace ... inside this function with the correct parameters in order to get your data

[*********************100%***********************]  1 of 1 completed

In [9]:
data.tail()

Price           Close       High        Low       Open    Volume
Ticker      000660.KS  000660.KS  000660.KS  000660.KS 000660.KS
Date
2026-04-30  1286000.0  1325000.0  1286000.0  1312000.0   3342342
2026-05-04  1447000.0  1450000.0  1333000.0  1339000.0   5776641
2026-05-06  1601000.0  1614000.0  1557000.0  1590000.0   6631934
2026-05-07  1654000.0  1665000.0  1567000.0  1622000.0   5860618
2026-05-08  1686000.0  1689000.0  1591000.0  1591000.0   4278087

**Calculate the 20-day and 50-day moving average**

Use Pandas methods to calculate the 20-day and 50-day moving averages for your ticker.

In [10]:
data[("MA_20", stock_ticker)] = data[("Close", stock_ticker)].rolling(window=20).mean()
data[("MA_50", stock_ticker)] = data[("Close", stock_ticker)].rolling(window=50).mean()

In [11]:
data.tail()

Price,Close,High,Low,Open,Volume,MA_20,MA_50
Ticker,000660.KS,000660.KS,000660.KS,000660.KS,000660.KS,000660.KS,000660.KS
Date,,,,,,,
2026-04-30,1286000.0,1325000.0,1286000.0,1312000.0,3342342,1126450.0,1.018523e+06
2026-05-04,1447000.0,1450000.0,1333000.0,1339000.0,5776641,1155000.0,1.029615e+06
2026-05-06,1601000.0,1614000.0,1557000.0,1590000.0,6631934,1190750.0,1.042690e+06
2026-05-07,1654000.0,1665000.0,1567000.0,1622000.0,5860618,1227650.0,1.056785e+06
2026-05-08,1686000.0,1689000.0,1591000.0,1591000.0,4278087,1260300.0,1.070442e+06

**Create a chart in `plotly` that shows both the 20-day and 50-day rolling average, plus the closing price, on the same graph**

Creating plots in `Plotly` takes a little more effort than in `matplotlib`. You'll be creating the same chart as you did in the prior exercise, but now using `plotly`. 

Can you add these 3 variables to the same line chart: (1) closing price, (2) 20-day moving average, and (3) 50-day moving average? 

Recall that in `plotly` each variable is added using a `trace`.

In [13]:
fig = go.Figure()

# add closing price
fig.add_trace(
    go.Scatter(
        x=data.index, y=data["Close"].squeeze(), mode="lines", name="Closing Price"
    )
)

# adding 20-day moving avg
fig.add_trace(
    go.Scatter(
        x=data.index,
        y=data["MA_20"].squeeze(),
        mode="lines",
        name="Moving Average 20 days",
    )
)

# add 50-day moving avg
fig.add_trace(
    go.Scatter(
        x=data.index,
        y=data["MA_50"].squeeze(),
        mode="lines",
        name="Moving Average 50 days",
    )
)

In [15]:
# customize your layout

fig.update_layout(
    title=dict(
        text="SK Hynix, 20-day and 50-day Moving Average Price", x=0.5, xanchor="center"
    ),
    xaxis_title="Date",
    yaxis_title="Price (KRW)",
    template="plotly_dark",
)

fig.show()