In [1]:
# Import libraries
import numpy as np
import yfinance as yf

In [3]:
# Use the `yfinance` library to download the front month S&P500 futures price data.
sp500_prices = yf.download("ES=F")["Close"]

[*********************100%***********************]  1 of 1 completed

In [4]:
sp500_prices.head()

Ticker         ES=F
Date
2026-04-13  6922.75
2026-04-14  7004.75
2026-04-15  7060.50
2026-04-16  7077.00
2026-04-17  7161.50

In [8]:
# Calculate the daily logarithmic returns of the futures prices.
log_returns = np.log(sp500_prices).diff()

In [9]:
log_returns.head()

Ticker          ES=F
Date
2026-04-13       NaN
2026-04-14  0.011775
2026-04-15  0.007927
2026-04-16  0.002334
2026-04-17  0.011869

In [10]:
# Calculate the standard deviation (volatility) of the logarithmic returns
# YOUR CODE HERE
daily_volatility = log_returns.std()

In [11]:
# Annualized the volatility
# There are approximately 252 trading days in a year
# YOUR CODE HERE
number_trading_days = 252
annualized_volatility = daily_volatility * np.sqrt(number_trading_days)
print()
print(f"annualized_volatility: {np.round(annualized_volatility * 100, 2)}%")
print()

annualized_volatility: Ticker
ES=F    10.0
dtype: float64%